version: '3'
services:
    client:
        container_name: aeropods-client
        image: 'aeropods/client:latest'
        command: 'yarn run dev'
        build:
            context: ../../packages/client
            dockerfile: Dockerfile.dev
        volumes:
            - ../../packages/client:/client
            - /client/node_modules
    api:
        container_name: aeropods-api
        image: 'aeropods/api:latest'
        command: 'yarn run dev'
        build:
            context: ../../packages/api
            dockerfile: Dockerfile.dev
        volumes:
            - ../../packages/api:/api
            - /api/node_modules
    server:
        container_name: aeropods-server
        image: 'aeropods/server:latest'
        build:
            context: ../../packages/server
            dockerfile: Dockerfile.dev
        ports:
            - '80:80'
        links:
            - client
            - api
